global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'users'
    static_configs:
      - targets: ['users:5091']

  - job_name: 'products'
    static_configs:
      - targets: ['products:5257']

  - job_name: 'orders'
    static_configs:
      - targets: ['orders:5059']

  - job_name: 'payments'
    static_configs:
      - targets: ['payments:5195']

  - job_name: 'inventory'
    static_configs:
      - targets: ['inventory:5138']

  - job_name: 'shipping'
    static_configs:
      - targets: ['shipping:5134']

  - job_name: 'cart'
    static_configs:
      - targets: ['cart:5151']

  - job_name: 'reviews'
    static_configs:
      - targets: ['reviews:5146']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:5292']

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:5221']

  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:5126']

  - job_name: 'support'
    static_configs:
      - targets: ['support:5185']
