apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: monitoring  
    app: analytics
    release: kube-prometheus
spec:
  selector:
    app: analytics
  ports:
    - name: http-metrics
      port: 8080        # Puerto expuesto dentro del cluster
      targetPort: 8080  # Puerto real del contenedor
